
  create table "public"."account_website" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "website" text not null,
    "summary" text,
    "markdown_url" text not null
      );


alter table "public"."account_website" enable row level security;

CREATE UNIQUE INDEX account_website_pkey ON public.account_website USING btree (id);

alter table "public"."account_website" add constraint "account_website_pkey" PRIMARY KEY using index "account_website_pkey";

grant delete on table "public"."account_website" to "anon";

grant insert on table "public"."account_website" to "anon";

grant references on table "public"."account_website" to "anon";

grant select on table "public"."account_website" to "anon";

grant trigger on table "public"."account_website" to "anon";

grant truncate on table "public"."account_website" to "anon";

grant update on table "public"."account_website" to "anon";

grant delete on table "public"."account_website" to "authenticated";

grant insert on table "public"."account_website" to "authenticated";

grant references on table "public"."account_website" to "authenticated";

grant select on table "public"."account_website" to "authenticated";

grant trigger on table "public"."account_website" to "authenticated";

grant truncate on table "public"."account_website" to "authenticated";

grant update on table "public"."account_website" to "authenticated";

grant delete on table "public"."account_website" to "service_role";

grant insert on table "public"."account_website" to "service_role";

grant references on table "public"."account_website" to "service_role";

grant select on table "public"."account_website" to "service_role";

grant trigger on table "public"."account_website" to "service_role";

grant truncate on table "public"."account_website" to "service_role";

grant update on table "public"."account_website" to "service_role";


