CREATE TABLE IF NOT EXISTS account (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  website text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE account ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access" ON account FOR ALL USING (true);